### ISSUE TITLE
Keyframe animations break when referenced before declaration

### ISSUE THREAD

**Issue by jantimon** [DigitecGalaxus/next-yak#320]
I've encountered an issue when using keyframe animations with next-yak's styled-components syntax. When a keyframe animation is referenced in an animation property before the keyframe is declared in the code, the animation doesn't work.

## Reproduction case

```jsx
import { styled, keyframes } from 'next-yak';

// This DOESN'T work - keyframe used before declaration
const Component = styled.div`
  animation: ${animationName} 1s ease;
`;

const animationName = keyframes`
  from { opacity: 0; }
  to { opacity: 1; }
`;

// This WORKS - keyframe declared before use
const workingAnimationName = keyframes`
  from { opacity: 0; }
  to { opacity: 1; }
`;

const WorkingComponent = styled.div`
  animation: ${workingAnimationName} 1s ease;
`;
```

## Expected behavior

Both components should correctly apply the animation, regardless of whether the keyframe is declared before or after it's referenced.

## Actual behavior

When examining the generated CSS, you can see the issue - For the non-working case, the animation name in the `.Component` class doesn't have the `:global()` wrapper, but the keyframe itself does:

```css
.Component {
  animation: animationName_i9blVg 1s ease; /* Missing :global() wrapper */
}

@keyframes :global(animationName_i9blVg) {
  from { opacity: 0; }
  to { opacity: 1; }
}
```

For the working case, both the animation property and keyframe declaration are properly scoped:

```css
.WorkingComponent {
  animation: :global(workingAnimationName_i9blVg) 1s ease;
}

@keyframes :global(workingAnimationName_i9blVg) {
  from { opacity: 0; }
  to { opacity: 1; }
}
```

## Environment

- next-yak version: 5.2.2
- Next.js version: 15.2.2
- Browser: Chrome 126 (but the issue is in the build step)
- OS: macOS Sonoma 14.5
