### ISSUE TITLE
Style duplication with dynamic mixins

### ISSUE THREAD

**Issue by PaulBlanche** [DigitecGalaxus/next-yak#367]
Given the following code : 
```ts
type Variant = { $type: "regular" | "bold" };

const dynamic = css<Variant>`
  ${({ $type }) => {
    if ($type === "regular") {
      return css`
        font-size: 14px;
        font-weight: 300;
      `;
    }
    if ($type === "bold") {
      return css`
        font-size: 14px;
        font-weight: 600;
      `;
    }
  }} 
`;

type ResponsiveVariant = Variant & { $breakpoint?: "laptop" | "tablet" };

const responsive = css<ResponsiveVariant>`
  ${({ $breakpoint = "tablet" }) => {
    if ($breakpoint === "laptop") {
      return css`
        @media screen and (min-width: 1024px) {
          ${dynamic}
        }
      `;
    } else if ($breakpoint === "tablet") {
      return css`
        @media screen and (min-width: 768px) {
          ${dynamic}
        }
      `;
    }
  }}
`;

export const S_regular = styled.p<ResponsiveVariant>`
    font-size: 14px;
    font-weight: 300;
    ${responsive}
  `;

export const S_bold = styled.p<ResponsiveVariant>`
    font-size: 14px;
    font-weight: 300;
    ${responsive}
  `;
```
I would expect the following classes to be generated : 
```css
.S_regular {
    font-size: 14px;
    font-weight: 300;
}
.S_bold {
    font-size: 14px;
    font-weight: 300;
}
@media screen and (min-width: 1024px) {
  .responsive_laptop_regular {
    font-size: 14px;
    font-weight: 300;
  }
}
@media screen and (min-width: 1024px) {
  .responsive_laptop_bold {
    font-size: 14px;
    font-weight: 600;
  }
}
@media screen and (min-width: 768px) {
  .responsive_tablet_regular {
    font-size: 14px;
    font-weight: 300;
  }
}
@media screen and (min-width: 768px) {
  .responsive_tablet_bold {
    font-size: 14px;
    font-weight: 600;
  }
}
```
Meaning a style for each `styled` component, and one class for each combination of props of the mixin `responsive`, regardless of the number of usage of it.

Instead we get this :
```css
.S_regular {
    font-size: 14px;
    font-weight: 300;
}
.S_bold {
    font-size: 14px;
    font-weight: 300;
}
@media screen and (min-width: 1024px) {
  .S_regular_responsive_laptop_regular {
    font-size: 14px;
    font-weight: 300;
  }
}
@media screen and (min-width: 1024px) {
  .S_regular_responsive_laptop_bold {
    font-size: 14px;
    font-weight: 600;
  }
}
@media screen and (min-width: 768px) {
  .S_regular_responsive_tablet_regular {
    font-size: 14px;
    font-weight: 300;
  }
}
@media screen and (min-width: 768px) {
  .S_regular_responsive_tablet_bold {
    font-size: 14px;
    font-weight: 600;
  }
}
@media screen and (min-width: 1024px) {
  .S_bold_responsive_laptop_regular {
    font-size: 14px;
    font-weight: 300;
  }
}
@media screen and (min-width: 1024px) {
  .S_bold_responsive_laptop_bold {
    font-size: 14px;
    font-weight: 600;
  }
}
@media screen and (min-width: 768px) {
  .S_bold_responsive_tablet_regular {
    font-size: 14px;
    font-weight: 300;
  }
}
@media screen and (min-width: 768px) {
  .S_bold_responsive_tablet_bold {
    font-size: 14px;
    font-weight: 600;
  }
}
```

All styles from `responsive` are duplicated for each `styled` component it is used in.

I could fix this by using inheritance like this : 
```ts
const base = styled.p<ResponsiveVariant>`
  ${responsive}
`

export const S_regular = styled(base)`
    font-size: 14px;
    font-weight: 300;
  `;

export const S_bold = styled(base)`
    font-size: 14px;
    font-weight: 300;
  `;
```
but the ordering changes and the media query classes from `responsive` comes **before** the classes it is supposed to override (which is expected, style inherited from base component should come before styles extending it).

In summary : 
- reusing the same mixin multiple times in a `styled` component results in duplicate classes
- using inheritance fixes the duplication, but changes the order of classes
