### ISSUE TITLE
exported mixin in nested selector placed outside if trailing semicolon is missing

### ISSUE THREAD

**Issue by PaulBlanche** [DigitecGalaxus/next-yak#372]
Given the following files:
```tsx
// other.tsx
export const Title = styled.h1`
  background-color: red;
`

export const mixin = css`
  background-color: blue;
`
```
```tsx
// main.tsx
import { Title, mixin } from "./other.tsx"

export const Center = styled.div`
  background-color: green;

  ${Title} {
    color: blue;
    ${mixin} // no semicolon
  }
`
```

We get the following css for `Center` : 
```css
.Center_yuj4Q {
  background-color: green;
  .Title_yuj3v {
    color: blue;
  }
  background-color: blue;
}
```

The `mixin` in the nested `Title` selector is instead applied outside.

I would expect this css instead : 
```css
.Center_yuj4Q {
  background-color: green;
  .Title_yuj3v {
    color: blue;
    background-color: blue;
  }
}
```

We get the expected behaviour if we add a semicolon after the mixin : 
```tsx
// main.tsx
import { Title, mixin } from "./other.tsx"

export const Center = styled.div`
  background-color: green;

  ${Title} {
    color: blue;
    ${mixin}; // semicolon
  }
`
```

Either it is a bug and `yak-swc` should handle the mixin without semicolon correctly, or it is "undefined" behavior caused by a malformed input (the missing semicolon) and `yak-swc` should throw instead of outputing incorrect css.

Here is a link to the repro in the playground : https://yak.js.org/playground?q=H4sIAPSOWmgCA51TTW%2FaQBDds3%2FFiCQVSBibQNTIkFx676mX3FjWC16xBme9oVYRraJW%2FVSlXir11PS3%2BJd1Zm0TUFAPRbKZN7v75s2bdcg4K%2F%2FgSwL%2BPFZ%2BeqWsll1IVaGWrPzcC1j50Bp5HtOs%2FM7ewoaVH9se7R6%2FkEsrzbUDCGO1rkMAVn7ZxSkvfFb%2BgmEYZsWoTk%2B2ddAcRwKVzncAIDfiqsVUay%2B1z7rP3A%2FDs4b4gBwg2ON3rV2%2FlIX1b%2FhiHFS4kR%2Bg%2FgqMg8fOOiNvi80LDE837sAWNm4XK39HMNV3Es0hfLpxnlHprTcZkbEPZCyevrWJTCVcuZMxN4sIWolNdY9ieNbqYlqreWKbvANuYUvW3zpmPC%2FyfIJ7WXmPfe%2FKT2iL08beJf1qwwe4MDIlU9ianHfRBoRrjIAlG6arwrdGpRHQG6FNDtZkPJcRCJ4B11nCp9Iq4dpFBRGchDUvAcNjxTXK%2BurcEMoILWHGDfaeW1%2BszFIa4BbsKgMtZ5aaBscB4VkNBoOBG2ZlPDH%2FcFpmShM1dszeVPVfN0u5NasFijQyhn5WdHbTeY%2FPt5u2P8RkdTlY%2BTMChOBU08TcXNwUmqnW3bDF8CKW8y6cxH3Rfx5iIOPL8JKCKtMBn5QGcL53%2BVAUzUZolaGlKO9x4Wm2uqT%2FX%2B6pOWqpLA7hcLkxiBon9%2F6h83gOidfctH2q4c9i%2FLuvDdXS4m3y84wLtZxHEPbC8%2BrS4TdzjO5IXfel3OET%2FwXfA3S%2BjAQAAA%3D%3D
