### ISSUE TITLE
Using properties inside strings should be replaced with the variable value instead of the name

### ISSUE THREAD

**Issue by Mad-Kat** [DigitecGalaxus/next-yak#73]
If you use a property inside double quotes, yak should replace the double quotes and the expression with the CSS variable.

So this:
```tsx
const Input = styled.input<{$placeholder: string}>`
  &::before {
    content: "${p => p.$placeholder}";
  }
`;
```

should result in:
```css
.Input {
  &::before {
    content: var(--🦬1sstj5p0);
  }
}
```

but results in:
```css
.Input {
  &::before {
    constent: "var(--🦬1sstj5p0)";
  }
}
```
